server {
    listen 127.0.0.1:80;
    server_name database.herd.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;

    location / {
        rewrite ^ "ADMINER_LOCATION" last;
    }

    access_log off;

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $herd_sock;
        fastcgi_index "ADMINER_LOCATION";
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "ADMINER_LOCATION";
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}