# Xdebug and XML decision logic
map $http_cookie $xdebug_present {
    default "default";
    "~*XDEBUG_SESSION=([^;]+)" "debug";
    "~*XDEBUG_PROFILE=([^;]+)" "debug";
    "~*XDEBUG_TRACE=([^;]+)" "debug";
}

map "$xdebug_present" $herd_sock {
    default "127.0.0.1:DEFAULT_PHP_PORT";
    "~^debug$" "127.0.0.1:DEFAULT_DEBUG_PHP_PORT";
}

# We need to repeat this for each isolated PHP version
map "$xdebug_present" $herd_sock_74 {
    default "127.0.0.1:PHP_74_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_74_PORT";
}

map "$xdebug_present" $herd_sock_80 {
    default "127.0.0.1:PHP_80_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_80_PORT";
}

map "$xdebug_present" $herd_sock_81 {
    default "127.0.0.1:PHP_81_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_81_PORT";
}

map "$xdebug_present" $herd_sock_82 {
    default "127.0.0.1:PHP_82_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_82_PORT";
}

map "$xdebug_present" $herd_sock_83 {
    default "127.0.0.1:PHP_83_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_83_PORT";
}

map "$xdebug_present" $herd_sock_84 {
    default "127.0.0.1:PHP_84_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_84_PORT";
}

map "$xdebug_present" $herd_sock_85 {
    default "127.0.0.1:PHP_85_PORT";
    "~^debug$" "127.0.0.1:DEBUG_PHP_85_PORT";
}
